import { beforeAll, describe, expect, test } from "vitest";
import { EmptyFileSystem, type LangiumDocument, URI } from "langium";
import { expandToString as s } from "langium/generate";
import { parseHelper } from "langium/test";
import { createXsmpServices } from "../../../src/language/xsmp-module.js";
import { Catalogue, isCatalogue } from "../../../src/language/generated/ast-partial.js";
import * as path from 'path';
import * as fs from 'fs';
import * as os from 'os';
import { SmpGenerator } from "../../../src/language/tools/smp/generator.js";
import { setGeneratedBy } from "../../../src/language/generator/generator.js";

let services: ReturnType<typeof createXsmpServices>;
let parse: ReturnType<typeof parseHelper<Catalogue>>;
let document: LangiumDocument<Catalogue> | undefined;

beforeAll(async () => {
  services = createXsmpServices(EmptyFileSystem);
  parse = parseHelper<Catalogue>(services.xsmpcat);

  await services.shared.workspace.WorkspaceManager.initializeWorkspace([]);
});

describe('SMP generator tests', () => {



  test('test catalogue', async () => {

    const generator = new SmpGenerator(services.shared);
    document = await parse(fs.readFileSync(path.resolve(__dirname, 'test.xsmpcat')).toString(), { documentUri: 'test.xsmpcat' });
    // disable generated by comment
    setGeneratedBy(false);

    // check for absensce of parser errors the classic way:
    //  deacivated, find a much more human readable way below!
    // expect(document.parseResult.parserErrors).toHaveLength(0);
    expect(
      // here we use a (tagged) template expression to create a human readable representation
      //  of the AST part we are interested in and that is to be compared to our expectation;
      // prior to the tagged template expression we check for validity of the parsed document object
      //  by means of the reusable function 'checkDocumentValid()' to sort out (critical) typos first;
      checkDocumentValid(document) ??
      await generator.doGenerateCatalogue(document.parseResult.value, undefined)
    ).toBe(fs.readFileSync(path.resolve(__dirname, 'test.smpcat')).toString());

    expect(
      // here we use a (tagged) template expression to create a human readable representation
      //  of the AST part we are interested in and that is to be compared to our expectation;
      // prior to the tagged template expression we check for validity of the parsed document object
      //  by means of the reusable function 'checkDocumentValid()' to sort out (critical) typos first;
      checkDocumentValid(document) ??
      await generator.doGeneratePackage(document.parseResult.value, undefined)
    ).toBe(fs.readFileSync(path.resolve(__dirname, 'test.smppkg')).toString());
  });

  test('writes catalogue and package files to disk before returning', async () => {
    const generator = new SmpGenerator(services.shared);
    document = await parse(fs.readFileSync(path.resolve(__dirname, 'test.xsmpcat')).toString(), { documentUri: 'write-test.xsmpcat' });
    setGeneratedBy(false);

    const parsed = checkDocumentValid(document);
    expect(parsed).toBeUndefined();

    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-generator-'));
    try {
      const projectUri = URI.file(tmpDir);
      const expectedCatalogue = await generator.doGenerateCatalogue(document!.parseResult.value, undefined);
      const expectedPackage = await generator.doGeneratePackage(document!.parseResult.value, undefined);

      await generator.generateCatalogue(document!.parseResult.value, projectUri, undefined);
      await generator.generatePackage(document!.parseResult.value, projectUri, undefined);

      const cataloguePath = path.join(tmpDir, 'smdl-gen', 'write-test.smpcat');
      const packagePath = path.join(tmpDir, 'smdl-gen', 'write-test.smppkg');

      expect(fs.existsSync(cataloguePath)).toBe(true);
      expect(fs.existsSync(packagePath)).toBe(true);
      expect(fs.readFileSync(cataloguePath).toString()).toBe(expectedCatalogue);
      expect(fs.readFileSync(packagePath).toString()).toBe(expectedPackage);
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });
});

function checkDocumentValid(document: LangiumDocument): string | undefined {
  return document.parseResult.parserErrors.length && s`
        Parser errors:
          ${document.parseResult.parserErrors.map(e => e.message).join('\n  ')}
    `
    || document.parseResult.value === undefined && `ParseResult is 'undefined'.`
    || !isCatalogue(document.parseResult.value) && `Root AST object is a ${document.parseResult.value.$type}, expected a '${Catalogue}'.`
    || undefined;
}
