import { inject } from 'langium';
import type { DeepPartial, Module } from 'langium';
import { type DefaultSharedModuleContext, type LangiumSharedServices, type LangiumServices, createDefaultModule, createDefaultSharedModule } from 'langium/lsp';
import { XsmpGeneratedSharedModule, XsmpasbGeneratedModule, XsmpcatGeneratedModule, XsmpcfgGeneratedModule, XsmplnkGeneratedModule, XsmpprojectGeneratedModule, XsmpsedGeneratedModule } from './generated/module.js';
import type { XsmpprojectServices } from './xsmpproject-module.js';
import { XsmpprojectModule } from './xsmpproject-module.js';
import { registerXsmpcatValidationChecks } from './validation/xsmpcat-validator.js';
import type { XsmpcatServices } from './xsmpcat-module.js';
import { XsmpcatModule } from './xsmpcat-module.js';
import { registerXsmpprojectValidationChecks } from './validation/xsmpproject-validator.js';
import { registerXsmpasbValidationChecks } from './validation/xsmpasb-validator.js';
import { registerXsmplnkValidationChecks } from './validation/xsmplnk-validator.js';
import { registerXsmpsedValidationChecks } from './validation/xsmpsed-validator.js';
import { XsmpWorkspaceManager } from './workspace/workspace-manager.js';
import { XsmpIndexManager } from './workspace/index-manager.js';
import { XsmpNodeKindProvider } from './lsp/node-kind-provider.js';
import { XsmpDocumentGenerator } from './workspace/document-generator.js';
import { XsmpTypeProvider } from './references/type-provider.js';
import { XsmpPathService } from './references/xsmp-path-service.js';
import { IdentifierPatternService } from './references/identifier-pattern-service.js';
import { XsmpTypedPathResolver } from './references/xsmp-typed-path-resolver.js';
import { XsmpcfgPathResolver } from './references/xsmpcfg-path-resolver.js';
import { Xsmpl2PathResolver } from './references/xsmpl2-path-resolver.js';
import { XsmpNodeInfoProvider } from './lsp/node-info-provider.js';
import { DocumentationHelper } from './utils/documentation-helper.js';
import { AttributeHelper } from './utils/attribute-helper.js';
import { ProjectManager } from './workspace/project-manager.js';
import { XsmpLanguageServer } from './lsp/language-server.js';
import { XsmpDocumentBuilder } from './workspace/document-builder.js';
import type { XsmpasbServices } from './xsmpasb-module.js';
import { XsmpasbModule } from './xsmpasb-module.js';
import type { XsmpcfgServices } from './xsmpcfg-module.js';
import { XsmpcfgModule } from './xsmpcfg-module.js';
import type { XsmplnkServices } from './xsmplnk-module.js';
import { XsmplnkModule } from './xsmplnk-module.js';
import type { XsmpsedServices } from './xsmpsed-module.js';
import { XsmpsedModule } from './xsmpsed-module.js';
import { registerXsmpcfgValidationChecks } from './validation/xsmpcfg-validator.js';
import { XsmpContributionRegistry } from './contributions/xsmp-contribution-registry.js';
import { XsmpDocumentUpdateHandler } from './lsp/document-update-handler.js';
import { SmpMirrorManager, SmpWorkspaceIndex, XsmpLangiumDocumentFactory } from './smp/index.js';
import { BuiltinDirectoryProvider } from './workspace/workspace-manager.js';

export type XsmpServices = LangiumServices & { shared: XsmpSharedServices; }
export interface XsmpModuleContext extends DefaultSharedModuleContext {
    readonly builtinDir?: string;
}
/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the Xsmp services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createXsmpServices(context: XsmpModuleContext): {
    shared: XsmpSharedServices,
    xsmpcat: XsmpcatServices,
    xsmpproject: XsmpprojectServices,
    xsmpasb: XsmpasbServices,
    xsmpcfg: XsmpcfgServices,
    xsmplnk: XsmplnkServices,
    xsmpsed: XsmpsedServices,
} {
    const runtimeSharedModule: Module<XsmpSharedServices, DeepPartial<XsmpSharedServices>> = {
        BuiltinDirectoryProvider: () => new BuiltinDirectoryProvider(context.builtinDir),
    };
    const shared = inject(
        createDefaultSharedModule(context),
        XsmpGeneratedSharedModule,
        XsmpSharedModule,
        runtimeSharedModule,
    );
    // XSMP Project
    const xsmpproject = inject(
        createDefaultModule({ shared }),
        XsmpprojectGeneratedModule,
        XsmpprojectModule
    );
    shared.ServiceRegistry.register(xsmpproject);
    registerXsmpprojectValidationChecks(xsmpproject);

    // XSMP Catalogue
    const xsmpcat = inject(
        createDefaultModule({ shared }),
        XsmpcatGeneratedModule,
        XsmpcatModule
    );
    shared.ServiceRegistry.register(xsmpcat);
    registerXsmpcatValidationChecks(xsmpcat);

    // XSMP Assembly
    const xsmpasb = inject(
        createDefaultModule({ shared }),
        XsmpasbGeneratedModule,
        XsmpasbModule
    );
    shared.ServiceRegistry.register(xsmpasb);
    registerXsmpasbValidationChecks(xsmpasb);

    // XSMP Configuration
    const xsmpcfg = inject(
        createDefaultModule({ shared }),
        XsmpcfgGeneratedModule,
        XsmpcfgModule
    );
    shared.ServiceRegistry.register(xsmpcfg);
    registerXsmpcfgValidationChecks(xsmpcfg);

    // XSMP LinkBase
    const xsmplnk = inject(
        createDefaultModule({ shared }),
        XsmplnkGeneratedModule,
        XsmplnkModule
    );
    shared.ServiceRegistry.register(xsmplnk);
    registerXsmplnkValidationChecks(xsmplnk);

    // XSMP Schedule
    const xsmpsed = inject(
        createDefaultModule({ shared }),
        XsmpsedGeneratedModule,
        XsmpsedModule
    );
    shared.ServiceRegistry.register(xsmpsed);
    registerXsmpsedValidationChecks(xsmpsed);

    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    shared.ContributionRegistry.setBootstrapServices({ shared, xsmpcat, xsmpproject, xsmpasb, xsmpcfg, xsmplnk, xsmpsed });
    return { shared, xsmpcat, xsmpproject, xsmpasb, xsmpcfg, xsmplnk, xsmpsed, };
}
/**
 * Declaration of custom shared services
 */
export interface XsmpAddedSharedServices {
    readonly BuiltinDirectoryProvider: BuiltinDirectoryProvider,
    readonly IdentifierPatternService: IdentifierPatternService,
    readonly PathService: XsmpPathService,
    readonly TypedPathResolver: XsmpTypedPathResolver,
    readonly CfgPathResolver: XsmpcfgPathResolver,
    readonly L2PathResolver: Xsmpl2PathResolver,
    readonly DocumentGenerator: XsmpDocumentGenerator,
    readonly TypeProvider: XsmpTypeProvider,
    readonly lsp: {
        readonly NodeInfoProvider: XsmpNodeInfoProvider,
    },
    readonly DocumentationHelper: DocumentationHelper,
    readonly AttributeHelper: AttributeHelper,
    readonly ContributionRegistry: XsmpContributionRegistry,
    readonly SmpMirrorManager: SmpMirrorManager,
    readonly SmpWorkspaceIndex: SmpWorkspaceIndex,
    readonly workspace: {
        ProjectManager: ProjectManager,
    },
}

/**
 * Union of Langium default shared services and Xsmp custom shared services
 */
export type XsmpSharedServices = LangiumSharedServices & XsmpAddedSharedServices;

export const XsmpSharedModule: Module<XsmpSharedServices, DeepPartial<XsmpSharedServices>> = {
    AttributeHelper: (services) => new AttributeHelper(services),
    IdentifierPatternService: (services) => new IdentifierPatternService(services),
    PathService: (services) => new XsmpPathService(services),
    TypedPathResolver: (services) => new XsmpTypedPathResolver(services),
    CfgPathResolver: (services) => new XsmpcfgPathResolver(services),
    L2PathResolver: (services) => new Xsmpl2PathResolver(services),
    DocumentGenerator: (services) => new XsmpDocumentGenerator(services),
    DocumentationHelper: (services) => new DocumentationHelper(services),
    ContributionRegistry: (services) => new XsmpContributionRegistry(services),
    SmpMirrorManager: (services) => new SmpMirrorManager(services),
    SmpWorkspaceIndex: () => new SmpWorkspaceIndex(),
    TypeProvider: (services) => new XsmpTypeProvider(services),
    lsp: {
        DocumentUpdateHandler: (services) => new XsmpDocumentUpdateHandler(services),
        NodeInfoProvider: (services) => new XsmpNodeInfoProvider(services),
        NodeKindProvider: () => new XsmpNodeKindProvider(),
        LanguageServer: (services) => new XsmpLanguageServer(services),
    },
    workspace: {
        LangiumDocumentFactory: (services) => new XsmpLangiumDocumentFactory(services),
        IndexManager: (services) => new XsmpIndexManager(services),
        WorkspaceManager: (services) => new XsmpWorkspaceManager(services),
        ProjectManager: (services) => new ProjectManager(services),
        DocumentBuilder: (services) => new XsmpDocumentBuilder(services),
    },
};
