import { afterEach, beforeAll, describe, expect, test } from 'vitest';
import { EmptyFileSystem, type LangiumDocument, URI } from 'langium';
import { clearDocuments, parseHelper } from 'langium/test';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { createXsmpServices } from 'xsmp';
import * as ast from 'xsmp/ast';
import { SmpImportService } from 'xsmp/smp';
import { detectSmpImportKind, getDefaultImportedXsmpPath, parseSmpXml } from 'xsmp/smp';
import { SmpGenerator } from '@xsmp/tool-smp';
import { setGeneratedBy } from 'xsmp/generator';
import { rebuildTestDocuments } from './test-services.js';

let services: ReturnType<typeof createXsmpServices>;
let parseProject: ReturnType<typeof parseHelper<ast.Project>>;
let parseCatalogue: ReturnType<typeof parseHelper<ast.Catalogue>>;
let parseConfiguration: ReturnType<typeof parseHelper<ast.Configuration>>;
let parseLinkBase: ReturnType<typeof parseHelper<ast.LinkBase>>;
let parseAssembly: ReturnType<typeof parseHelper<ast.Assembly>>;
let parseSchedule: ReturnType<typeof parseHelper<ast.Schedule>>;
const tempDirs: string[] = [];
const documents: LangiumDocument[] = [];

beforeAll(async () => {
    services = createXsmpServices(EmptyFileSystem);
    parseProject = parseHelper<ast.Project>(services.xsmpproject);
    parseCatalogue = parseHelper<ast.Catalogue>(services.xsmpcat);
    parseConfiguration = parseHelper<ast.Configuration>(services.xsmpcfg);
    parseLinkBase = parseHelper<ast.LinkBase>(services.xsmplnk);
    parseAssembly = parseHelper<ast.Assembly>(services.xsmpasb);
    parseSchedule = parseHelper<ast.Schedule>(services.xsmpsed);
    await services.shared.workspace.WorkspaceManager.initializeWorkspace([]);
});

afterEach(async () => {
    if (documents.length > 0) {
        await clearDocuments(services.shared, documents.splice(0));
    }
    services.shared.SmpWorkspaceIndex.setEligibleSourcePaths([]);
    await services.shared.SmpWorkspaceIndex.rebuildSearchRoots([]);
    while (tempDirs.length > 0) {
        fs.rmSync(tempDirs.pop()!, { recursive: true, force: true });
    }
});

describe('SMP importer', () => {
    test('detects supported roots and default output paths', () => {
        expect(getDefaultImportedXsmpPath('/tmp/demo.smpcat')).toBe('/tmp/demo.xsmpcat');
        expect(getDefaultImportedXsmpPath('/tmp/demo.smpcfg')).toBe('/tmp/demo.xsmpcfg');
        expect(getDefaultImportedXsmpPath('/tmp/demo.smplnk')).toBe('/tmp/demo.xsmplnk');
        expect(getDefaultImportedXsmpPath('/tmp/demo.smpasb')).toBe('/tmp/demo.xsmpasb');
        expect(getDefaultImportedXsmpPath('/tmp/demo.smpsed')).toBe('/tmp/demo.xsmpsed');
        expect(detectSmpImportKind(parseSmpXml('<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue"/>'))).toBe('catalogue');
        expect(detectSmpImportKind(parseSmpXml('<?xml version="1.0" encoding="UTF-8"?>\n<!--Generated By SmpTool-->\n<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue"/>'))).toBe('catalogue');
        expect(detectSmpImportKind(parseSmpXml('<Configuration:Configuration xmlns:Configuration="http://www.ecss.nl/smp/2025/Smdl/Configuration"/>'))).toBe('configuration');
        expect(detectSmpImportKind(parseSmpXml('<LinkBase:LinkBase xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase"/>'))).toBe('linkbase');
        expect(detectSmpImportKind(parseSmpXml('<Assembly:Assembly xmlns:Assembly="http://www.ecss.nl/smp/2025/Smdl/Assembly"/>'))).toBe('assembly');
        expect(detectSmpImportKind(parseSmpXml('<Schedule:Schedule xmlns:Schedule="http://www.ecss.nl/smp/2025/Smdl/Schedule"/>'))).toBe('schedule');
    });

    test('imports a catalogue and regenerates the same SMP XML', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-cat-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'test.smpcat');
        fs.copyFileSync(path.resolve(__dirname, 'test.smpcat'), inputPath);

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');
        const projectDocument = await parseProject(
            'project \'demo\' using \'ECSS_SMP_2020\'\nsource \'src\'\n',
            { documentUri: URI.file(path.join(tempDir, 'xsmp.project')).toString() }
        );
        const document = await parseCatalogue(importedText, { documentUri: URI.file(path.join(tempDir, 'src', 'test.xsmpcat')).toString() });
        documents.push(projectDocument, document);
        await rebuildTestDocuments(services, [projectDocument, document]);

        expect(result.kind).toBe('catalogue');
        expect(result.warnings).toEqual([]);
        expect(document.parseResult.parserErrors).toHaveLength(0);
        expect(ast.isCatalogue(document.parseResult.value)).toBe(true);

        setGeneratedBy(false);
        const generator = new SmpGenerator(services.shared);
        const regenerated = await generator.doGenerateCatalogue(document.parseResult.value, undefined);
        expect(regenerated).toBe(fs.readFileSync(path.resolve(__dirname, 'test.smpcat'), 'utf-8'));
    });

    test('imports 2025 Reference.Type and Realization into XSMP catalogue syntax', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-cat-2025-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'demo.smpcat');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="demo" Name="Demo">
  <Namespace Name="demo">
    <Type xsi:type="Catalogue:Interface" Id="demo.IBus" Name="IBus"/>
    <Type xsi:type="Catalogue:Model" Id="demo.Child" Name="Child"/>
    <Type xsi:type="Catalogue:Model" Id="demo.Root" Name="Root">
      <Realization Id="demo.Root.bus" Name="bus">
        <Interface xlink:href="#demo.IBus" xlink:title="demo.IBus"/>
      </Realization>
      <Reference Id="demo.Root.childRef" Name="childRef">
        <Type xlink:href="#demo.Child" xlink:title="demo.Child"/>
      </Reference>
    </Type>
  </Namespace>
</Catalogue:Catalogue>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');

        expect(result.warnings).toEqual([]);
        expect(importedText).toContain('reference Child childRef');
        expect(importedText).toContain('realization IBus bus');
    });

    test('imports a configuration and regenerates the same SMP XML', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-cfg-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'test.smpcfg');
        fs.copyFileSync(path.resolve(__dirname, 'test.smpcfg'), inputPath);

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');
        const projectDocument = await parseProject(
            'project \'demo\' using \'ECSS_SMP_2025\'\nsource \'src\'\ntool \'smp\'\n',
            { documentUri: URI.file(path.join(tempDir, 'xsmp.project')).toString() }
        );
        const document = await parseConfiguration(importedText, { documentUri: URI.file(path.join(tempDir, 'src', 'test.xsmpcfg')).toString() });
        documents.push(projectDocument, document);

        expect(result.kind).toBe('configuration');
        expect(result.warnings).toEqual([]);
        expect(document.parseResult.parserErrors).toHaveLength(0);
        expect(ast.isConfiguration(document.parseResult.value)).toBe(true);

        setGeneratedBy(false);
        const generator = new SmpGenerator(services.shared);
        const regenerated = await generator.doGenerateConfiguration(document.parseResult.value, undefined);
        expect(regenerated).toBe(fs.readFileSync(path.resolve(__dirname, 'test.smpcfg'), 'utf-8'));
    });

    test('imports StartIndex array values into configuration syntax', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-cfg-start-index-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'demo.smpcfg');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Configuration:Configuration xmlns:Configuration="http://www.ecss.nl/smp/2025/Smdl/Configuration" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="cfg" Name="Demo">
  <Component Path=".">
    <FieldValue xsi:type="Types:Int32ArrayValue" Field="simpleValues">
      <StartIndex>2</StartIndex>
      <ItemValue xsi:type="Types:Int32Value" Value="5"/>
      <ItemValue xsi:type="Types:Int32Value" Value="6"/>
    </FieldValue>
  </Component>
</Configuration:Configuration>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');

        expect(result.warnings).toEqual([]);
        expect(importedText).toContain('simpleValues = [2: 5i32, 6i32]');
    });

    test('imports nullptr defaults for reference-like parameters without quoted strings', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-nullptr-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'demo.smpcat');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="demo" Name="Demo">
  <Namespace Name="demo">
    <Type xsi:type="Catalogue:Interface" Id="demo.ITarget" Name="ITarget"/>
    <Type xsi:type="Catalogue:Interface" Id="demo.IHolder" Name="IHolder" Visibility="public">
      <Operation Id="demo.IHolder.SetTarget" Name="SetTarget" Visibility="public">
        <Parameter Id="demo.IHolder.SetTarget.target" Name="target" Direction="inout">
          <Type xlink:href="#demo.ITarget" xlink:title="demo.ITarget"/>
          <Default xsi:type="Types:String8Value" Value="nullptr"/>
        </Parameter>
      </Operation>
    </Type>
  </Namespace>
</Catalogue:Catalogue>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');

        expect(result.warnings).toEqual([]);
        expect(importedText).toContain('def void SetTarget(inout ITarget target = nullptr)');
        expect(importedText).not.toContain('"nullptr"');
        expect(importedText).not.toContain('public def void SetTarget');
    });

    test('warns when importing catalogue default values with non-zero StartIndex', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-cat-start-index-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'demo.smpcat');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="demo" Name="Demo">
  <Namespace Name="demo">
    <Type xsi:type="Types:PrimitiveType" Id="demo.Int32" Name="Int32"/>
    <Type xsi:type="Types:Array" Id="demo.SimpleIntQuad" Name="SimpleIntQuad">
      <ItemType xlink:href="#demo.Int32" xlink:title="demo.Int32"/>
      <Size xsi:type="Types:Int32Value" Value="4"/>
    </Type>
    <Type xsi:type="Catalogue:Model" Id="demo.Root" Name="Root">
      <Field Id="demo.Root.simpleValues" Name="simpleValues">
        <Type xlink:href="#demo.SimpleIntQuad" xlink:title="demo.SimpleIntQuad"/>
        <Default xsi:type="Types:Int32ArrayValue">
          <StartIndex>1</StartIndex>
          <ItemValue xsi:type="Types:Int32Value" Value="2"/>
        </Default>
      </Field>
    </Type>
  </Namespace>
</Catalogue:Catalogue>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });

        expect(result.warnings).toEqual([
            "Catalogue array default value StartIndex='1' is not representable in XSMP and was discarded.",
        ]);
    });

    test('imports a link base and regenerates the same SMP XML', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-lnk-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'test.smplnk');
        fs.copyFileSync(path.resolve(__dirname, 'test.smplnk'), inputPath);

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');
        const document = await parseLinkBase(importedText, { documentUri: URI.file(result.outputPath).toString() });

        expect(result.kind).toBe('linkbase');
        expect(result.warnings).toEqual([]);
        expect(document.parseResult.parserErrors).toHaveLength(0);
        expect(ast.isLinkBase(document.parseResult.value)).toBe(true);

        setGeneratedBy(false);
        const generator = new SmpGenerator(services.shared);
        const regenerated = await generator.doGenerateLinkBase(document.parseResult.value, undefined);
        expect(regenerated).toBe(fs.readFileSync(path.resolve(__dirname, 'test.smplnk'), 'utf-8'));
    });

    test('imports interface links with back references and preserves unsupported links as field links', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-lnk-interface-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'demo.smplnk');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<LinkBase:LinkBase xmlns:Elements="http://www.ecss.nl/smp/2019/Core/Elements" xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="Demo" Name="Demo">
  <Component Path="/">
    <Link xsi:type="LinkBase:InterfaceLink">
      <OwnerPath>svc</OwnerPath>
      <Reference>ref</Reference>
      <ClientPath>client</ClientPath>
      <BackReference>back</BackReference>
    </Link>
    <Link xsi:type="LinkBase:CustomLink">
      <OwnerPath>raw.out</OwnerPath>
      <ClientPath>raw.in</ClientPath>
    </Link>
  </Component>
</LinkBase:LinkBase>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');
        const document = await parseLinkBase(importedText, { documentUri: URI.file(result.outputPath).toString() });

        expect(result.kind).toBe('linkbase');
        expect(result.warnings).toEqual([
            "Unsupported link type 'LinkBase:CustomLink'; importing as field link.",
        ]);
        expect(importedText).toContain('interface link svc.ref -> client:back');
        expect(importedText).toContain('field link raw.out -> raw.in');
        expect(document.parseResult.parserErrors).toHaveLength(0);
    });

    test('imports an assembly and regenerates the same SMP XML', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-asb-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'test.smpasb');
        fs.copyFileSync(path.resolve(__dirname, 'test.smpasb'), inputPath);

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');
        const document = await parseAssembly(importedText, { documentUri: URI.file(result.outputPath).toString() });

        expect(result.kind).toBe('assembly');
        expect(result.warnings).toEqual([]);
        expect(document.parseResult.parserErrors).toHaveLength(0);
        expect(ast.isAssembly(document.parseResult.value)).toBe(true);

        setGeneratedBy(false);
        const generator = new SmpGenerator(services.shared);
        const regenerated = await generator.doGenerateAssembly(document.parseResult.value, undefined);
        expect(regenerated).toBe(fs.readFileSync(path.resolve(__dirname, 'test.smpasb'), 'utf-8'));
    });

    test('imports assembly invocations, handlers, and unresolved document references into usable XSMP assembly syntax', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-asb-fallbacks-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'demo.smpasb');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Assembly:Assembly xmlns:Elements="http://www.ecss.nl/smp/2019/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2019/Core/Types" xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:Assembly="http://www.ecss.nl/smp/2025/Smdl/Assembly" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="Demo" Name="Demo">
  <ComponentConfiguration InstancePath=".">
    <Invocation xsi:type="Assembly:OperationCall" Operation="bootstrap">
      <Parameter Parameter="count">
        <Value xsi:type="Types:Int32Value" Value="1"/>
      </Parameter>
    </Invocation>
    <Invocation xsi:type="Assembly:PropertyValue" Property="mode">
      <Value xsi:type="Types:String8Value" Value="safe"/>
    </Invocation>
    <Invocation xsi:type="Assembly:CustomInvocation"/>
    <GlobalEventHandler EntryPointName="Start" GlobalEventName="Boot"/>
    <FieldValue xsi:type="Types:BoolValue" Value="true" Field="enabled"/>
  </ComponentConfiguration>
  <Model Name="Root">
    <Assembly Container="child" Name="Child" Assembly="missing/dep.smpasb" Configuration="configs/cfg.smpcfg" LinkBase="links/demo.smplnk">
      <Argument Name="count" xsi:type="Assembly:Int32Argument" Value="2"/>
      <Argument Name="mode" xsi:type="Assembly:StringArgument" Value="safe"/>
      <ModelConfiguration InstancePath="child">
        <Invocation xsi:type="Assembly:PropertyValue" Property="mode">
          <Value xsi:type="Types:String8Value" Value="warmup"/>
        </Invocation>
      </ModelConfiguration>
    </Assembly>
    <Model Container="child" Name="Leaf" Implementation="demo::Leaf">
      <GlobalEventHandler EntryPointName="OnTick" GlobalEventName="Tick"/>
    </Model>
  </Model>
</Assembly:Assembly>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');
        const document = await parseAssembly(importedText, { documentUri: URI.file(result.outputPath).toString() });

        expect(result.kind).toBe('assembly');
        expect(result.warnings).toEqual([
            "Unsupported assembly invocation type 'Assembly:CustomInvocation'.",
            'Missing model implementation; using placeholder string implementation.',
            "Could not resolve assembly reference 'missing/dep.smpasb'; using 'dep'.",
            "Could not resolve assembly configuration 'configs/cfg.smpcfg'; using 'cfg'.",
            "Could not resolve assembly link base 'links/demo.smplnk'; using 'demo'.",
        ]);
        expect(importedText).toContain('configure .');
        expect(importedText).toContain('call bootstrap(count=1i32)');
        expect(importedText).toContain('property mode = "safe"');
        expect(importedText).toContain('/* unsupported invocation */');
        expect(importedText).toContain('subscribe Start -> "Boot"');
        expect(importedText).toContain('enabled = true');
        expect(importedText).toContain('Root: "__missing__"');
        expect(importedText).toContain('child += Child: dep<count = 2, mode = "safe"> using config cfg using link demo');
        expect(importedText).toContain('configure child');
        expect(importedText).toContain('property mode = "warmup"');
        expect(importedText).toContain('child += Leaf: demo.Leaf');
        expect(importedText).toContain('subscribe OnTick -> "Tick"');
        expect(document.parseResult.parserErrors).toHaveLength(0);
    });

    test('rejects malformed assembly files that do not declare a root model', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-asb-malformed-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'broken.smpasb');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Assembly:Assembly xmlns:Elements="http://www.ecss.nl/smp/2019/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2019/Core/Types" xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:Assembly="http://www.ecss.nl/smp/2025/Smdl/Assembly" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="Broken" Name="Broken">
  <ComponentConfiguration InstancePath=".">
    <FieldValue xsi:type="Types:Int32Value" Value="1" Field="count"/>
  </ComponentConfiguration>
</Assembly:Assembly>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        await expect(importer.importFile({ inputPath })).rejects.toThrow(/missing root Model element/u);
    });

    test('imports a schedule and regenerates the same SMP XML', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-sed-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'test.smpsed');
        fs.copyFileSync(path.resolve(__dirname, 'test.smpsed'), inputPath);

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');
        const document = await parseSchedule(importedText, { documentUri: URI.file(result.outputPath).toString() });

        expect(result.kind).toBe('schedule');
        expect(result.warnings).toEqual([]);
        expect(document.parseResult.parserErrors).toHaveLength(0);
        expect(ast.isSchedule(document.parseResult.value)).toBe(true);

        setGeneratedBy(false);
        const generator = new SmpGenerator(services.shared);
        const regenerated = await generator.doGenerateSchedule(document.parseResult.value, undefined);
        expect(regenerated).toBe(fs.readFileSync(path.resolve(__dirname, 'test.smpsed'), 'utf-8'));
    });

    test('imports schedule headers, task execution, and unsupported nodes into readable schedule syntax', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-sed-runtime-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'demo.smpsed');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Schedule:Schedule xmlns:Elements="http://www.ecss.nl/smp/2019/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2019/Core/Types" xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:Assembly="http://www.ecss.nl/smp/2025/Smdl/Assembly" xmlns:Schedule="http://www.ecss.nl/smp/2025/Smdl/Schedule" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="BootFlow" Name="BootFlow" EpochTime="2026-01-01T00:00:00Z" MissionStart="PT10S">
  <Task Id="BootFlow.Worker" Name="Worker"/>
  <Task Id="BootFlow.Main" Name="Main">
    <Activity Id="BootFlow.Main.ExecuteWorker" Name="ExecuteWorker" xsi:type="Schedule:ExecuteTask" Root="/AssemblyRoot">
      <Task xlink:title="Worker" xlink:href="#BootFlow.Worker"/>
      <Argument Name="count" xsi:type="Schedule:Int32Argument" Value="2"/>
      <Argument Name="mode" xsi:type="Schedule:StringArgument" Value="safe"/>
    </Activity>
    <Activity Id="BootFlow.Main.Custom" Name="Custom" xsi:type="Schedule:CustomActivity"/>
  </Task>
  <Event Id="BootFlow.Startup" Name="Startup" xsi:type="Schedule:GlobalEventTriggeredEvent" CycleTime="PT30S" RepeatCount="4" StartEvent="BootCompleted" StopEvent="ShutdownRequested" TimeKind="SimulationTime" Delay="PT5S">
    <Task xlink:title="Main" xlink:href="#BootFlow.Main"/>
  </Event>
  <Event Id="BootFlow.Unsupported" Name="Unsupported" xsi:type="Schedule:CustomEvent">
    <Task xlink:title="Worker" xlink:href="#BootFlow.Worker"/>
  </Event>
</Schedule:Schedule>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');
        const document = await parseSchedule(importedText, { documentUri: URI.file(result.outputPath).toString() });

        expect(result.kind).toBe('schedule');
        expect(result.warnings).toEqual([
            "Unsupported schedule activity type 'Schedule:CustomActivity'.",
            "Unsupported schedule event type 'Schedule:CustomEvent'.",
        ]);
        expect(importedText).toContain('schedule BootFlow epoch "2026-01-01T00:00:00Z" mission "PT10S"');
        expect(importedText).toContain('task Worker');
        expect(importedText).toContain('execute Worker<count = 2, mode = "safe"> at /AssemblyRoot');
        expect(importedText).toContain('/* unsupported activity */');
        expect(importedText).toContain('event Main on "BootCompleted" until "ShutdownRequested" using simulation delay "PT5S" cycle "PT30S" repeat 4');
        expect(importedText).toContain('/* unsupported event for Worker */');
        expect(document.parseResult.parserErrors).toHaveLength(0);
    });

    test('falls back to task titles when external schedule task ids cannot be resolved', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-sed-missing-id-'));
        tempDirs.push(tempDir);
        fs.writeFileSync(path.join(tempDir, 'external.smpsed'), `<?xml version="1.0" encoding="UTF-8"?>
<Schedule:Schedule xmlns:Schedule="http://www.ecss.nl/smp/2025/Smdl/Schedule" xmlns:Elements="http://www.ecss.nl/smp/2019/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2019/Core/Types" xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:Assembly="http://www.ecss.nl/smp/2025/Smdl/Assembly" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="Hidden" Name="Hidden">
  <Task Id="Hidden.OtherTask" Name="OtherTask"/>
</Schedule:Schedule>
`, 'utf-8');
        const inputPath = path.join(tempDir, 'main.smpsed');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Schedule:Schedule xmlns:Schedule="http://www.ecss.nl/smp/2025/Smdl/Schedule" xmlns:Elements="http://www.ecss.nl/smp/2019/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2019/Core/Types" xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:Assembly="http://www.ecss.nl/smp/2025/Smdl/Assembly" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="Main" Name="Main">
  <Task Id="Main.Root" Name="Root">
    <Activity Id="Main.Root.ExecuteTask1" Name="ExecuteTask1" xsi:type="Schedule:ExecuteTask">
      <Task xlink:title="FallbackTask" xlink:href="external.smpsed#Hidden/MissingTask"/>
    </Activity>
  </Task>
</Schedule:Schedule>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');

        expect(result.warnings).toEqual([
            "Could not resolve external task reference id 'Hidden/MissingTask' from 'external.smpsed#Hidden/MissingTask'; falling back to title or fragment text.",
        ]);
        expect(importedText).toContain('execute FallbackTask');
    });

    test('rejects unsupported SMP XML roots', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-pkg-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'test.smppkg');
        fs.copyFileSync(path.resolve(__dirname, 'test.smppkg'), inputPath);

        const importer = new SmpImportService(services.shared);
        await expect(importer.importFile({ inputPath })).rejects.toThrow(/Unsupported SMP XML root/u);
    });

    test('resolves external catalogue href ids by loading the referenced SMP file', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-external-cat-'));
        tempDirs.push(tempDir);
        const dependencyPath = path.join(tempDir, 'dependency.smpcat');
        const inputPath = path.join(tempDir, 'main.smpcat');
        fs.writeFileSync(dependencyPath, `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="dep" Name="dependency">
  <Namespace Name="dep">
    <Type xsi:type="Types:Structure" Id="dep.struct.custom" Name="ExternalStruct"/>
  </Namespace>
</Catalogue:Catalogue>
`, 'utf-8');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="main" Name="main">
  <Namespace Name="main">
    <Type xsi:type="Types:Structure" Id="main.LocalStruct" Name="LocalStruct">
      <Field Id="main.LocalStruct.external" Name="external">
        <Type xlink:href="dependency.smpcat#dep.struct.custom"/>
      </Field>
    </Type>
  </Namespace>
</Catalogue:Catalogue>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');

        expect(result.warnings).toEqual([]);
        expect(importedText).toContain('field dep.ExternalStruct external');
    });

    test('resolves external catalogue href ids from a prebuilt workspace index', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-indexed-cat-'));
        tempDirs.push(tempDir);
        const dependencyDirectory = path.join(tempDir, 'deps');
        const inputDirectory = path.join(tempDir, 'inbox');
        fs.mkdirSync(dependencyDirectory, { recursive: true });
        fs.mkdirSync(inputDirectory, { recursive: true });

        fs.writeFileSync(path.join(dependencyDirectory, 'dependency.smpcat'), `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="dep" Name="dependency">
  <Namespace Name="dep">
    <Type xsi:type="Types:Structure" Id="dep.struct.prebuilt" Name="PrebuiltStruct"/>
  </Namespace>
</Catalogue:Catalogue>
`, 'utf-8');

        const inputPath = path.join(inputDirectory, 'main.smpcat');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="main" Name="main">
  <Namespace Name="main">
    <Type xsi:type="Types:Structure" Id="main.LocalStruct" Name="LocalStruct">
      <Field Id="main.LocalStruct.external" Name="external">
        <Type xlink:href="dependency.smpcat#dep.struct.prebuilt"/>
      </Field>
    </Type>
  </Namespace>
</Catalogue:Catalogue>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const workspaceIndex = services.shared.SmpWorkspaceIndex;
        await workspaceIndex.rebuildSearchRoots([tempDir]);

        const result = await importer.renderImportedDocument({
            inputPath,
            outputUri: URI.file(path.join(inputDirectory, 'main.xsmpcat')),
            workspaceIndex,
        });

        expect(result.warnings).toEqual([]);
        expect(result.content).toContain('field dep.PrebuiltStruct external');
    });

    test('resolves external catalogue href ids from indexed subdirectories during standalone imports', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-subdir-cat-'));
        tempDirs.push(tempDir);
        const dependencyDirectory = path.join(tempDir, 'deps');
        fs.mkdirSync(dependencyDirectory, { recursive: true });

        fs.writeFileSync(path.join(dependencyDirectory, 'dependency.smpcat'), `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="dep" Name="dependency">
  <Namespace Name="dep">
    <Type xsi:type="Types:Structure" Id="dep.struct.indexed" Name="IndexedStruct"/>
  </Namespace>
</Catalogue:Catalogue>
`, 'utf-8');

        const inputPath = path.join(tempDir, 'main.smpcat');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="main" Name="main">
  <Namespace Name="main">
    <Type xsi:type="Types:Structure" Id="main.LocalStruct" Name="LocalStruct">
      <Field Id="main.LocalStruct.external" Name="external">
        <Type xlink:href="dependency.smpcat#dep.struct.indexed"/>
      </Field>
    </Type>
  </Namespace>
</Catalogue:Catalogue>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');

        expect(result.warnings).toEqual([]);
        expect(importedText).toContain('field dep.IndexedStruct external');
    });

    test('warns when multiple indexed SMP files match the same external href without selecting one arbitrarily', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-ambiguous-cat-'));
        tempDirs.push(tempDir);
        const selectedPath = path.join(tempDir, 'a', 'dependency.smpcat');
        const secondaryPath = path.join(tempDir, 'b', 'dependency.smpcat');
        fs.mkdirSync(path.dirname(selectedPath), { recursive: true });
        fs.mkdirSync(path.dirname(secondaryPath), { recursive: true });

        fs.writeFileSync(selectedPath, `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="dep" Name="dependency">
  <Namespace Name="dep">
    <Type xsi:type="Types:Structure" Id="dep.struct.selected" Name="SelectedStruct"/>
  </Namespace>
</Catalogue:Catalogue>
`, 'utf-8');
        fs.writeFileSync(secondaryPath, `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="dep" Name="dependency">
  <Namespace Name="dep">
    <Type xsi:type="Types:Structure" Id="dep.struct.selected" Name="SecondaryStruct"/>
  </Namespace>
</Catalogue:Catalogue>
`, 'utf-8');

        const inputPath = path.join(tempDir, 'main.smpcat');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="main" Name="main">
  <Namespace Name="main">
    <Type xsi:type="Types:Structure" Id="main.LocalStruct" Name="LocalStruct">
      <Field Id="main.LocalStruct.external" Name="external">
        <Type xlink:href="dependency.smpcat#dep.struct.selected"/>
      </Field>
    </Type>
  </Namespace>
</Catalogue:Catalogue>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');

        expect(result.warnings).toEqual([
            `Multiple SMP files match external field type href 'dependency.smpcat': '${selectedPath}', '${secondaryPath}'. Not selecting one.`,
        ]);
        expect(importedText).toContain('field dep.struct.selected external');
    });

    test('resolves external configuration includes by id when no xlink:title is present', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-external-cfg-'));
        tempDirs.push(tempDir);
        const dependencyPath = path.join(tempDir, 'base.smpcfg');
        const inputPath = path.join(tempDir, 'main.smpcfg');
        fs.writeFileSync(dependencyPath, `<?xml version="1.0" encoding="UTF-8"?>
<Configuration:Configuration xmlns:Configuration="http://www.ecss.nl/smp/2025/Smdl/Configuration" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="cfg.base.custom" Name="BaseConfig"/>
`, 'utf-8');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Configuration:Configuration xmlns:Configuration="http://www.ecss.nl/smp/2025/Smdl/Configuration" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="cfg.main" Name="MainConfig">
  <Include Path=".">
    <Configuration xlink:href="base.smpcfg#cfg.base.custom"/>
  </Include>
</Configuration:Configuration>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');

        expect(result.warnings).toEqual([]);
        expect(importedText).toContain('include BaseConfig at .');
    });

    test('resolves external assembly, configuration, and link base file references to document names', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-external-asb-'));
        tempDirs.push(tempDir);
        fs.writeFileSync(path.join(tempDir, 'dep.smpasb'), `<?xml version="1.0" encoding="UTF-8"?>
<Assembly:Assembly xmlns:Assembly="http://www.ecss.nl/smp/2025/Smdl/Assembly" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="dep" Name="ImportedAssembly">
  <Model Name="Root" Implementation="demo::Root"/>
</Assembly:Assembly>
`, 'utf-8');
        fs.writeFileSync(path.join(tempDir, 'cfg.smpcfg'), `<?xml version="1.0" encoding="UTF-8"?>
<Configuration:Configuration xmlns:Configuration="http://www.ecss.nl/smp/2025/Smdl/Configuration" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="cfg" Name="ImportedConfig"/>
`, 'utf-8');
        fs.writeFileSync(path.join(tempDir, 'links.smplnk'), `<?xml version="1.0" encoding="UTF-8"?>
<LinkBase:LinkBase xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:Elements="http://www.ecss.nl/smp/2019/Core/Elements" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="lnk" Name="ImportedLinks"/>
`, 'utf-8');
        const inputPath = path.join(tempDir, 'main.smpasb');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Assembly:Assembly xmlns:Assembly="http://www.ecss.nl/smp/2025/Smdl/Assembly" xmlns:Elements="http://www.ecss.nl/smp/2019/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2019/Core/Types" xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="main" Name="Main">
  <Model Name="Root" Implementation="demo::Root">
    <Assembly Container="child" Name="Child" Assembly="dep.smpasb" Configuration="cfg.smpcfg" LinkBase="links.smplnk"/>
  </Model>
</Assembly:Assembly>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');

        expect(result.warnings).toEqual([]);
        expect(importedText).toContain('child += Child: ImportedAssembly using config ImportedConfig using link ImportedLinks');
    });

    test('resolves external schedule task href ids by loading the referenced SMP file', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-external-sed-'));
        tempDirs.push(tempDir);
        fs.writeFileSync(path.join(tempDir, 'hidden.smpsed'), `<?xml version="1.0" encoding="UTF-8"?>
<Schedule:Schedule xmlns:Schedule="http://www.ecss.nl/smp/2025/Smdl/Schedule" xmlns:Elements="http://www.ecss.nl/smp/2019/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2019/Core/Types" xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:Assembly="http://www.ecss.nl/smp/2025/Smdl/Assembly" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="Hidden" Name="Hidden">
  <Task Id="Child" Name="Child"/>
</Schedule:Schedule>
`, 'utf-8');
        const inputPath = path.join(tempDir, 'main.smpsed');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Schedule:Schedule xmlns:Schedule="http://www.ecss.nl/smp/2025/Smdl/Schedule" xmlns:Elements="http://www.ecss.nl/smp/2019/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2019/Core/Types" xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:Assembly="http://www.ecss.nl/smp/2025/Smdl/Assembly" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="Main" Name="Main">
  <Task Id="Root" Name="Root">
    <Activity Id="Root.ExecuteTask1" Name="ExecuteTask1" xsi:type="Schedule:ExecuteTask">
      <Task xlink:href="hidden.smpsed#Child"/>
    </Activity>
  </Task>
</Schedule:Schedule>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');

        expect(result.warnings).toEqual([]);
        expect(importedText).toContain('execute Hidden.Child');
    });
});
