import { afterEach, beforeAll, describe, expect, test } from 'vitest';
import { EmptyFileSystem, type LangiumDocument, URI } from 'langium';
import { clearDocuments, parseHelper } from 'langium/test';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { createXsmpServices } from 'xsmp';
import * as ast from 'xsmp/ast';
import { SmpImportService } from 'xsmp/smp';
import { detectSmpImportKind, getDefaultImportedXsmpPath, parseSmpXml } from 'xsmp/smp';
import { SmpGenerator } from '@xsmp/tool-smp';
import { setGeneratedBy } from 'xsmp/generator';

let services: ReturnType<typeof createXsmpServices>;
let parseProject: ReturnType<typeof parseHelper<ast.Project>>;
let parseCatalogue: ReturnType<typeof parseHelper<ast.Catalogue>>;
let parseConfiguration: ReturnType<typeof parseHelper<ast.Configuration>>;
let parseLinkBase: ReturnType<typeof parseHelper<ast.LinkBase>>;
let parseAssembly: ReturnType<typeof parseHelper<ast.Assembly>>;
let parseSchedule: ReturnType<typeof parseHelper<ast.Schedule>>;
const tempDirs: string[] = [];
const documents: LangiumDocument[] = [];

beforeAll(async () => {
    services = createXsmpServices(EmptyFileSystem);
    parseProject = parseHelper<ast.Project>(services.xsmpproject);
    parseCatalogue = parseHelper<ast.Catalogue>(services.xsmpcat);
    parseConfiguration = parseHelper<ast.Configuration>(services.xsmpcfg);
    parseLinkBase = parseHelper<ast.LinkBase>(services.xsmplnk);
    parseAssembly = parseHelper<ast.Assembly>(services.xsmpasb);
    parseSchedule = parseHelper<ast.Schedule>(services.xsmpsed);
    await services.shared.workspace.WorkspaceManager.initializeWorkspace([]);
});

afterEach(async () => {
    if (documents.length > 0) {
        await clearDocuments(services.shared, documents.splice(0));
    }
    while (tempDirs.length > 0) {
        fs.rmSync(tempDirs.pop()!, { recursive: true, force: true });
    }
});

describe('SMP importer', () => {
    test('detects supported roots and default output paths', () => {
        expect(getDefaultImportedXsmpPath('/tmp/demo.smpcat')).toBe('/tmp/demo.xsmpcat');
        expect(getDefaultImportedXsmpPath('/tmp/demo.smpcfg')).toBe('/tmp/demo.xsmpcfg');
        expect(getDefaultImportedXsmpPath('/tmp/demo.smplnk')).toBe('/tmp/demo.xsmplnk');
        expect(getDefaultImportedXsmpPath('/tmp/demo.smpasb')).toBe('/tmp/demo.xsmpasb');
        expect(getDefaultImportedXsmpPath('/tmp/demo.smpsed')).toBe('/tmp/demo.xsmpsed');
        expect(detectSmpImportKind(parseSmpXml('<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue"/>'))).toBe('catalogue');
        expect(detectSmpImportKind(parseSmpXml('<?xml version="1.0" encoding="UTF-8"?>\n<!--Generated By SmpTool-->\n<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue"/>'))).toBe('catalogue');
        expect(detectSmpImportKind(parseSmpXml('<Configuration:Configuration xmlns:Configuration="http://www.ecss.nl/smp/2025/Smdl/Configuration"/>'))).toBe('configuration');
        expect(detectSmpImportKind(parseSmpXml('<LinkBase:LinkBase xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase"/>'))).toBe('linkbase');
        expect(detectSmpImportKind(parseSmpXml('<Assembly:Assembly xmlns:Assembly="http://www.ecss.nl/smp/2025/Smdl/Assembly"/>'))).toBe('assembly');
        expect(detectSmpImportKind(parseSmpXml('<Schedule:Schedule xmlns:Schedule="http://www.ecss.nl/smp/2025/Smdl/Schedule"/>'))).toBe('schedule');
    });

    test('imports a catalogue and regenerates the same SMP XML', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-cat-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'test.smpcat');
        fs.copyFileSync(path.resolve(__dirname, 'test.smpcat'), inputPath);

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');
        const document = await parseCatalogue(importedText, { documentUri: URI.file(result.outputPath).toString() });

        expect(result.kind).toBe('catalogue');
        expect(result.warnings).toEqual([]);
        expect(document.parseResult.parserErrors).toHaveLength(0);
        expect(ast.isCatalogue(document.parseResult.value)).toBe(true);

        setGeneratedBy(false);
        const generator = new SmpGenerator(services.shared);
        const regenerated = await generator.doGenerateCatalogue(document.parseResult.value, undefined);
        expect(regenerated).toBe(fs.readFileSync(path.resolve(__dirname, 'test.smpcat'), 'utf-8'));
    });

    test('imports a configuration and regenerates the same SMP XML', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-cfg-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'test.smpcfg');
        fs.copyFileSync(path.resolve(__dirname, 'test.smpcfg'), inputPath);

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');
        const projectDocument = await parseProject(
            `project 'demo' using 'ECSS_SMP_2025'\nsource 'src'\ntool 'smp'\n`,
            { documentUri: URI.file(path.join(tempDir, 'xsmp.project')).toString() }
        );
        const document = await parseConfiguration(importedText, { documentUri: URI.file(path.join(tempDir, 'src', 'test.xsmpcfg')).toString() });
        documents.push(projectDocument, document);

        expect(result.kind).toBe('configuration');
        expect(result.warnings).toEqual([]);
        expect(document.parseResult.parserErrors).toHaveLength(0);
        expect(ast.isConfiguration(document.parseResult.value)).toBe(true);

        setGeneratedBy(false);
        const generator = new SmpGenerator(services.shared);
        const regenerated = await generator.doGenerateConfiguration(document.parseResult.value, undefined);
        expect(regenerated).toBe(fs.readFileSync(path.resolve(__dirname, 'test.smpcfg'), 'utf-8'));
    });

    test('imports a link base and regenerates the same SMP XML', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-lnk-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'test.smplnk');
        fs.copyFileSync(path.resolve(__dirname, 'test.smplnk'), inputPath);

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');
        const document = await parseLinkBase(importedText, { documentUri: URI.file(result.outputPath).toString() });

        expect(result.kind).toBe('linkbase');
        expect(result.warnings).toEqual([]);
        expect(document.parseResult.parserErrors).toHaveLength(0);
        expect(ast.isLinkBase(document.parseResult.value)).toBe(true);

        setGeneratedBy(false);
        const generator = new SmpGenerator(services.shared);
        const regenerated = await generator.doGenerateLinkBase(document.parseResult.value, undefined);
        expect(regenerated).toBe(fs.readFileSync(path.resolve(__dirname, 'test.smplnk'), 'utf-8'));
    });

    test('imports an assembly and regenerates the same SMP XML', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-asb-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'test.smpasb');
        fs.copyFileSync(path.resolve(__dirname, 'test.smpasb'), inputPath);

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');
        const document = await parseAssembly(importedText, { documentUri: URI.file(result.outputPath).toString() });

        expect(result.kind).toBe('assembly');
        expect(result.warnings).toEqual([]);
        expect(document.parseResult.parserErrors).toHaveLength(0);
        expect(ast.isAssembly(document.parseResult.value)).toBe(true);

        setGeneratedBy(false);
        const generator = new SmpGenerator(services.shared);
        const regenerated = await generator.doGenerateAssembly(document.parseResult.value, undefined);
        expect(regenerated).toBe(fs.readFileSync(path.resolve(__dirname, 'test.smpasb'), 'utf-8'));
    });

    test('imports a schedule and regenerates the same SMP XML', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-sed-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'test.smpsed');
        fs.copyFileSync(path.resolve(__dirname, 'test.smpsed'), inputPath);

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');
        const document = await parseSchedule(importedText, { documentUri: URI.file(result.outputPath).toString() });

        expect(result.kind).toBe('schedule');
        expect(result.warnings).toEqual([]);
        expect(document.parseResult.parserErrors).toHaveLength(0);
        expect(ast.isSchedule(document.parseResult.value)).toBe(true);

        setGeneratedBy(false);
        const generator = new SmpGenerator(services.shared);
        const regenerated = await generator.doGenerateSchedule(document.parseResult.value, undefined);
        expect(regenerated).toBe(fs.readFileSync(path.resolve(__dirname, 'test.smpsed'), 'utf-8'));
    });

    test('rejects unsupported SMP XML roots', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-pkg-'));
        tempDirs.push(tempDir);
        const inputPath = path.join(tempDir, 'test.smppkg');
        fs.copyFileSync(path.resolve(__dirname, 'test.smppkg'), inputPath);

        const importer = new SmpImportService(services.shared);
        await expect(importer.importFile({ inputPath })).rejects.toThrow(/Unsupported SMP XML root/u);
    });

    test('resolves external catalogue href ids by loading the referenced SMP file', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-external-cat-'));
        tempDirs.push(tempDir);
        const dependencyPath = path.join(tempDir, 'dependency.smpcat');
        const inputPath = path.join(tempDir, 'main.smpcat');
        fs.writeFileSync(dependencyPath, `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="dep" Name="dependency">
  <Namespace Name="dep">
    <Type xsi:type="Types:Structure" Id="dep.struct.custom" Name="ExternalStruct"/>
  </Namespace>
</Catalogue:Catalogue>
`, 'utf-8');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="main" Name="main">
  <Namespace Name="main">
    <Type xsi:type="Types:Structure" Id="main.LocalStruct" Name="LocalStruct">
      <Field Id="main.LocalStruct.external" Name="external">
        <Type xlink:href="dependency.smpcat#dep.struct.custom"/>
      </Field>
    </Type>
  </Namespace>
</Catalogue:Catalogue>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');

        expect(result.warnings).toEqual([]);
        expect(importedText).toContain('field dep.ExternalStruct external');
    });

    test('resolves external configuration includes by id when no xlink:title is present', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-external-cfg-'));
        tempDirs.push(tempDir);
        const dependencyPath = path.join(tempDir, 'base.smpcfg');
        const inputPath = path.join(tempDir, 'main.smpcfg');
        fs.writeFileSync(dependencyPath, `<?xml version="1.0" encoding="UTF-8"?>
<Configuration:Configuration xmlns:Configuration="http://www.ecss.nl/smp/2025/Smdl/Configuration" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="cfg.base.custom" Name="BaseConfig"/>
`, 'utf-8');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Configuration:Configuration xmlns:Configuration="http://www.ecss.nl/smp/2025/Smdl/Configuration" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="cfg.main" Name="MainConfig">
  <Include Path=".">
    <Configuration xlink:href="base.smpcfg#cfg.base.custom"/>
  </Include>
</Configuration:Configuration>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');

        expect(result.warnings).toEqual([]);
        expect(importedText).toContain('include BaseConfig at .');
    });

    test('resolves external assembly, configuration, and link base file references to document names', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-external-asb-'));
        tempDirs.push(tempDir);
        fs.writeFileSync(path.join(tempDir, 'dep.smpasb'), `<?xml version="1.0" encoding="UTF-8"?>
<Assembly:Assembly xmlns:Assembly="http://www.ecss.nl/smp/2025/Smdl/Assembly" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="dep" Name="ImportedAssembly">
  <Model Name="Root" Implementation="demo::Root"/>
</Assembly:Assembly>
`, 'utf-8');
        fs.writeFileSync(path.join(tempDir, 'cfg.smpcfg'), `<?xml version="1.0" encoding="UTF-8"?>
<Configuration:Configuration xmlns:Configuration="http://www.ecss.nl/smp/2025/Smdl/Configuration" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="cfg" Name="ImportedConfig"/>
`, 'utf-8');
        fs.writeFileSync(path.join(tempDir, 'links.smplnk'), `<?xml version="1.0" encoding="UTF-8"?>
<LinkBase:LinkBase xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:Elements="http://www.ecss.nl/smp/2019/Core/Elements" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="lnk" Name="ImportedLinks"/>
`, 'utf-8');
        const inputPath = path.join(tempDir, 'main.smpasb');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Assembly:Assembly xmlns:Assembly="http://www.ecss.nl/smp/2025/Smdl/Assembly" xmlns:Elements="http://www.ecss.nl/smp/2019/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2019/Core/Types" xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="main" Name="Main">
  <Model Name="Root" Implementation="demo::Root">
    <Assembly Container="child" Name="Child" Assembly="dep.smpasb" Configuration="cfg.smpcfg" LinkBase="links.smplnk"/>
  </Model>
</Assembly:Assembly>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');

        expect(result.warnings).toEqual([]);
        expect(importedText).toContain('child += Child: ImportedAssembly using config ImportedConfig using link ImportedLinks');
    });

    test('resolves external schedule task href ids by loading the referenced SMP file', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-import-external-sed-'));
        tempDirs.push(tempDir);
        fs.writeFileSync(path.join(tempDir, 'hidden.smpsed'), `<?xml version="1.0" encoding="UTF-8"?>
<Schedule:Schedule xmlns:Schedule="http://www.ecss.nl/smp/2025/Smdl/Schedule" xmlns:Elements="http://www.ecss.nl/smp/2019/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2019/Core/Types" xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:Assembly="http://www.ecss.nl/smp/2025/Smdl/Assembly" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="Hidden" Name="Hidden">
  <Task Id="Child" Name="Child"/>
</Schedule:Schedule>
`, 'utf-8');
        const inputPath = path.join(tempDir, 'main.smpsed');
        fs.writeFileSync(inputPath, `<?xml version="1.0" encoding="UTF-8"?>
<Schedule:Schedule xmlns:Schedule="http://www.ecss.nl/smp/2025/Smdl/Schedule" xmlns:Elements="http://www.ecss.nl/smp/2019/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2019/Core/Types" xmlns:LinkBase="http://www.ecss.nl/smp/2025/Smdl/LinkBase" xmlns:Assembly="http://www.ecss.nl/smp/2025/Smdl/Assembly" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="Main" Name="Main">
  <Task Id="Root" Name="Root">
    <Activity Id="Root.ExecuteTask1" Name="ExecuteTask1" xsi:type="Schedule:ExecuteTask">
      <Task xlink:href="hidden.smpsed#Child"/>
    </Activity>
  </Task>
</Schedule:Schedule>
`, 'utf-8');

        const importer = new SmpImportService(services.shared);
        const result = await importer.importFile({ inputPath });
        const importedText = fs.readFileSync(result.outputPath, 'utf-8');

        expect(result.warnings).toEqual([]);
        expect(importedText).toContain('execute Hidden.Child');
    });
});
