import { afterEach, beforeAll, describe, expect, test } from "vitest";
import { EmptyFileSystem, type LangiumDocument, URI } from "langium";
import { expandToString as s } from "langium/generate";
import { clearDocuments, parseHelper } from "langium/test";
import { createXsmpServices } from 'xsmp';
import * as ast from 'xsmp/ast';
import * as path from 'path';
import * as fs from 'fs';
import * as os from 'os';
import { SmpGenerator } from '@xsmp/tool-smp';
import { setGeneratedBy } from 'xsmp/generator';
import { rebuildTestDocuments } from './test-services.js';

let services: ReturnType<typeof createXsmpServices>;
let parseProject: ReturnType<typeof parseHelper<ast.Project>>;
let parse: ReturnType<typeof parseHelper<ast.Catalogue>>;
let document: LangiumDocument<ast.Catalogue> | undefined;
const documents: LangiumDocument[] = [];
const tempDirs: string[] = [];

beforeAll(async () => {
  services = createXsmpServices(EmptyFileSystem);
  parseProject = parseHelper<ast.Project>(services.xsmpproject);
  parse = parseHelper<ast.Catalogue>(services.xsmpcat);

  await services.shared.workspace.WorkspaceManager.initializeWorkspace([]);
});

afterEach(async () => {
  if (documents.length > 0) {
    await clearDocuments(services.shared, documents.splice(0));
  }
  while (tempDirs.length > 0) {
    fs.rmSync(tempDirs.pop()!, { recursive: true, force: true });
  }
});

describe('SMP generator tests', () => {



  test('test catalogue', async () => {

    const generator = new SmpGenerator(services.shared);
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-generator-cat-'));
    tempDirs.push(tempDir);
    const projectDocument = await parseProject(
      `project 'demo' using 'ECSS_SMP_2020'\nsource 'src'\n`,
      { documentUri: URI.file(path.join(tempDir, 'xsmp.project')).toString() },
    );
    document = await parse(fs.readFileSync(path.resolve(__dirname, 'test.xsmpcat')).toString(), {
      documentUri: URI.file(path.join(tempDir, 'src', 'test.xsmpcat')).toString(),
    });
    documents.push(projectDocument, document);
    await rebuildTestDocuments(services, [projectDocument, document]);
    // disable generated by comment
    setGeneratedBy(false);

    // check for absensce of parser errors the classic way:
    //  deacivated, find a much more human readable way below!
    // expect(document.parseResult.parserErrors).toHaveLength(0);
    expect(
      // here we use a (tagged) template expression to create a human readable representation
      //  of the AST part we are interested in and that is to be compared to our expectation;
      // prior to the tagged template expression we check for validity of the parsed document object
      //  by means of the reusable function 'checkDocumentValid()' to sort out (critical) typos first;
      checkDocumentValid(document) ??
      await generator.doGenerateCatalogue(document.parseResult.value, undefined)
    ).toBe(fs.readFileSync(path.resolve(__dirname, 'test.smpcat')).toString());

    expect(
      // here we use a (tagged) template expression to create a human readable representation
      //  of the AST part we are interested in and that is to be compared to our expectation;
      // prior to the tagged template expression we check for validity of the parsed document object
      //  by means of the reusable function 'checkDocumentValid()' to sort out (critical) typos first;
      checkDocumentValid(document) ??
      await generator.doGeneratePackage(document.parseResult.value, undefined)
    ).toBe(fs.readFileSync(path.resolve(__dirname, 'test.smppkg')).toString());
  });

  test('writes catalogue and package files to disk before returning', async () => {
    const generator = new SmpGenerator(services.shared);
    document = await parse(fs.readFileSync(path.resolve(__dirname, 'test.xsmpcat')).toString(), { documentUri: 'write-test.xsmpcat' });
    setGeneratedBy(false);

    const parsed = checkDocumentValid(document);
    expect(parsed).toBeUndefined();

    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-generator-'));
    try {
      const projectUri = URI.file(tmpDir);
      const expectedCatalogue = await generator.doGenerateCatalogue(document!.parseResult.value, undefined);
      const expectedPackage = await generator.doGeneratePackage(document!.parseResult.value, undefined);

      await generator.generateCatalogue(document!.parseResult.value, projectUri, undefined);
      await generator.generatePackage(document!.parseResult.value, projectUri, undefined);

      const cataloguePath = path.join(tmpDir, 'smdl-gen', 'write-test.smpcat');
      const packagePath = path.join(tmpDir, 'smdl-gen', 'write-test.smppkg');

      expect(fs.existsSync(cataloguePath)).toBe(true);
      expect(fs.existsSync(packagePath)).toBe(true);
      expect(fs.readFileSync(cataloguePath).toString()).toBe(expectedCatalogue);
      expect(fs.readFileSync(packagePath).toString()).toBe(expectedPackage);
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  test('serializes Reference using Interface in 2020 and Type in 2025', async () => {
    const generator = new SmpGenerator(services.shared);
    setGeneratedBy(false);

    const catalogue2020 = await parseCatalogueInProject(`
catalogue Demo

namespace demo
{
  public interface IBus
  {
  }

  public model Root
  {
    reference demo.IBus bus
  }
}
`, 'ECSS_SMP_2020');
    const xml2020 = checkDocumentValid(catalogue2020) ?? await generator.doGenerateCatalogue(catalogue2020.parseResult.value, undefined);
    expect(xml2020).toContain('<Reference');
    expect(xml2020).toContain('<Interface');
    expect(xml2020).not.toContain('<Reference Id="demo.Root.bus" Name="bus" Lower="1" Upper="1">\n        <Type');

    const catalogue2025 = await parseCatalogueInProject(`
catalogue Demo

namespace demo
{
  public interface IBus
  {
  }

  public model Child
  {
  }

  public model Root
  {
    reference demo.Child childRef
  }
}
`, 'ECSS_SMP_2025');
    const xml2025 = checkDocumentValid(catalogue2025) ?? await generator.doGenerateCatalogue(catalogue2025.parseResult.value, undefined);
    expect(xml2025).toContain('<Reference');
    expect(xml2025).toContain('<Type');
  });
});

function checkDocumentValid(document: LangiumDocument): string | undefined {
  return document.parseResult.parserErrors.length && s`
        Parser errors:
          ${document.parseResult.parserErrors.map(e => e.message).join('\n  ')}
    `
    || document.parseResult.value === undefined && `ParseResult is 'undefined'.`
    || !ast.isCatalogue(document.parseResult.value) && `Root AST object is a ${document.parseResult.value.$type}, expected a '${ast.Catalogue.$type}'.`
    || undefined;
}

async function parseCatalogueInProject(source: string, standard: 'ECSS_SMP_2020' | 'ECSS_SMP_2025'): Promise<LangiumDocument<ast.Catalogue>> {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-generator-inline-'));
  tempDirs.push(tempDir);
  const projectDocument = await parseProject(
    `project 'demo' using '${standard}'\nsource 'src'\n`,
    { documentUri: URI.file(path.join(tempDir, 'xsmp.project')).toString() },
  );
  const catalogueDocument = await parse(source, {
    documentUri: URI.file(path.join(tempDir, 'src', 'demo.xsmpcat')).toString(),
  });
  documents.push(projectDocument, catalogueDocument);
  await rebuildTestDocuments(services, [projectDocument, catalogueDocument], false);
  return catalogueDocument;
}
