import { afterEach, beforeEach, describe, expect, test } from 'vitest';
import { Cancellation, type LangiumDocument, URI } from 'langium';
import { NodeFileSystem } from 'langium/node';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { FileChangeType, type DidChangeWatchedFilesParams, type LocationLink, type TextDocumentPositionParams } from 'vscode-languageserver';
import { createXsmpServices } from 'xsmp';
import { createBuiltinTestXsmpServices } from '../test-services.js';

let tempDir: string;

beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xsmp-smp-mirror-'));
});

afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
});

describe('SMP mirror workspace support', () => {
    test('creates XSMP mirrors for SMP source files and resolves XSMP references against them', async () => {
        const projectDir = createProject(tempDir, 'app', `
project 'app'
using 'ECSS_SMP_2025'
source 'src'
`, {
            'src/types.smpcat': `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="dep" Name="types">
  <Namespace Name="dep">
    <Type xsi:type="Types:Structure" Id="dep.ExternalType" Name="ExternalType" Uuid="aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"/>
  </Namespace>
</Catalogue:Catalogue>
`,
            'src/app.xsmpcat': `
catalogue app

namespace app
{
    /** @uuid 11111111-1111-1111-1111-111111111111 */
    struct UsesExternal
    {
        field dep.ExternalType external
    }
}
`,
        });

        const services = await createBuiltinTestXsmpServices(NodeFileSystem);
        await services.shared.workspace.WorkspaceManager.initializeWorkspace([
            { name: 'app', uri: URI.file(projectDir).toString() },
        ]);

        const mirrorUri = services.shared.SmpWorkspaceIndex.getMirrorUriForSourcePath(path.join(projectDir, 'src', 'types.smpcat'));
        expect(mirrorUri).toBeDefined();
        const mirrorDocument = mirrorUri && services.shared.workspace.LangiumDocuments.getDocument(mirrorUri);
        expect(mirrorDocument).toBeDefined();

        const appDocument = services.shared.workspace.LangiumDocuments.getDocument(URI.file(path.join(projectDir, 'src', 'app.xsmpcat')));
        expect(appDocument?.diagnostics?.some(diagnostic => diagnostic.message.includes('Could not resolve reference'))).not.toBe(true);
    });

    test('resolves cross-project references against SMP mirrors from dependency source folders', async () => {
        const foundationDir = createProject(tempDir, 'foundation', `
project 'foundation'
using 'ECSS_SMP_2025'
source 'src'
`, {
            'src/foundation_catalogue.smpcat': `<?xml version="1.0" encoding="UTF-8"?>
<!--Generated By SmpTool-1.97.0-->
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="foundation" Name="foundation_catalogue">
  <Namespace Id="demo" Name="demo">
    <Namespace Id="demo.foundation" Name="foundation">
      <Type xsi:type="Types:Structure" Id="demo.foundation.ExternalType" Name="ExternalType" Visibility="public" Uuid="dddddddd-dddd-dddd-dddd-dddddddddddd"/>
    </Namespace>
  </Namespace>
</Catalogue:Catalogue>
`,
        });
        const avionicsDir = createProject(tempDir, 'avionics', `
project 'avionics'
using 'ECSS_SMP_2025'
source 'src'
dependency 'foundation'
`, {
            'src/avionics_catalogue.xsmpcat': `
catalogue avionics_catalogue

namespace demo::avionics
{
    /** @uuid eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee */
    struct UsesExternal
    {
        field demo.foundation.ExternalType external
    }
}
`,
        });

        const services = createXsmpServices(NodeFileSystem);
        await services.shared.ContributionRegistry.ready;
        await services.shared.workspace.WorkspaceManager.initializeWorkspace([
            { name: 'foundation', uri: URI.file(foundationDir).toString() },
            { name: 'avionics', uri: URI.file(avionicsDir).toString() },
        ]);

        const mirrorUri = services.shared.SmpWorkspaceIndex.getMirrorUriForSourcePath(path.join(foundationDir, 'src', 'foundation_catalogue.smpcat'));
        expect(mirrorUri).toBeDefined();
        const mirrorDocument = mirrorUri && services.shared.workspace.LangiumDocuments.getDocument(mirrorUri);
        expect(mirrorDocument).toBeDefined();
        const avionicsDocument = services.shared.workspace.LangiumDocuments.getDocument(URI.file(path.join(avionicsDir, 'src', 'avionics_catalogue.xsmpcat')));
        expect(avionicsDocument?.diagnostics?.some(diagnostic => diagnostic.message.includes('Could not resolve reference'))).not.toBe(true);

        const referenceOffset = avionicsDocument?.textDocument.getText().indexOf('demo.foundation.ExternalType');
        expect(referenceOffset).toBeGreaterThanOrEqual(0);
        const definitions = await services.xsmpcat.lsp.DefinitionProvider?.getDefinition(
            avionicsDocument!,
            positionParams(avionicsDocument!, referenceOffset! + 'demo.foundation.'.length),
        ) ?? [];

        expectMirrorLocation(
            definitions,
            mirrorUri!,
            mirrorDocument!,
            'ExternalType',
        );
    });

    test('marks workspace ready only after dependency SMP mirrors are available', async () => {
        const foundationDir = createProject(tempDir, 'foundation', `
project 'foundation'
using 'ECSS_SMP_2025'
source 'src'
`, {
            'src/foundation_catalogue.smpcat': `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="foundation" Name="foundation_catalogue">
  <Namespace Id="demo" Name="demo">
    <Namespace Id="demo.foundation" Name="foundation">
      <Type xsi:type="Types:Float" Id="demo.foundation.TemperatureC" Name="TemperatureC" Visibility="public" Uuid="01010101-0101-0101-0101-010101010101" PrimitiveType="Float32"/>
    </Namespace>
  </Namespace>
</Catalogue:Catalogue>
`,
        });
        const avionicsDir = createProject(tempDir, 'avionics', `
project 'avionics'
using 'ECSS_SMP_2025'
source 'src'
dependency 'foundation'
`, {
            'src/avionics_catalogue.xsmpcat': `
catalogue avionics_catalogue

namespace demo::avionics
{
    /** @uuid 13131313-1313-1313-1313-131313131313 */
    struct UsesExternal
    {
        field demo.foundation.TemperatureC external
    }
}
`,
        });

        const services = createXsmpServices(NodeFileSystem);
        await services.shared.ContributionRegistry.ready;
        void services.shared.workspace.WorkspaceManager.initializeWorkspace([
            { name: 'foundation', uri: URI.file(foundationDir).toString() },
            { name: 'avionics', uri: URI.file(avionicsDir).toString() },
        ]);

        await services.shared.workspace.WorkspaceManager.ready;

        const mirrorUri = services.shared.SmpWorkspaceIndex.getMirrorUriForSourcePath(path.join(foundationDir, 'src', 'foundation_catalogue.smpcat'));
        expect(mirrorUri).toBeDefined();
        expect(mirrorUri && services.shared.workspace.LangiumDocuments.getDocument(mirrorUri)).toBeDefined();

        const avionicsDocument = services.shared.workspace.LangiumDocuments.getDocument(URI.file(path.join(avionicsDir, 'src', 'avionics_catalogue.xsmpcat')));
        expect(avionicsDocument?.diagnostics?.some(diagnostic => diagnostic.message.includes('Could not resolve reference'))).not.toBe(true);
    });

    test('prefers a real XSMP homologue and reports the SMP source as ignored', async () => {
        const projectDir = createProject(tempDir, 'app', `
project 'app'
using 'ECSS_SMP_2025'
source 'src'
`, {
            'src/types.smpcat': `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="dep" Name="types">
  <Namespace Name="dep">
    <Type xsi:type="Types:Structure" Id="dep.ExternalType" Name="ExternalType" Uuid="bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"/>
  </Namespace>
</Catalogue:Catalogue>
`,
            'src/types.xsmpcat': `
catalogue types

namespace dep
{
    /** @uuid 22222222-2222-2222-2222-222222222222 */
    struct ExternalType
    {
    }
}
`,
        });

        const services = await createBuiltinTestXsmpServices(NodeFileSystem);
        await services.shared.workspace.WorkspaceManager.initializeWorkspace([
            { name: 'app', uri: URI.file(projectDir).toString() },
        ]);

        const mirrorUri = services.shared.SmpWorkspaceIndex.getMirrorUriForSourcePath(path.join(projectDir, 'src', 'types.smpcat'));
        expect(mirrorUri).toBeDefined();
        expect(mirrorUri && services.shared.workspace.LangiumDocuments.getDocument(mirrorUri)).toBeUndefined();

        const diagnostics = services.shared.SmpMirrorManager.getSourceDiagnosticEntries()
            .find(entry => entry.uri.fsPath === path.join(projectDir, 'src', 'types.smpcat'));
        expect(diagnostics?.diagnostics.map(diagnostic => diagnostic.message)).toEqual([
            expect.stringContaining("Ignoring 'types.smpcat' because 'types.xsmpcat' is present"),
        ]);
    });

    test('ignores SMP files under smdl-gen and generates outputs from mirrored SMP sources', async () => {
        const projectDir = createProject(tempDir, 'app', `
project 'app'
using 'ECSS_SMP_2025'
source 'src'
tool 'smp'
`, {
            'src/types.smpcat': `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="dep" Name="types">
  <Namespace Name="dep">
    <Type xsi:type="Types:Structure" Id="dep.ExternalType" Name="ExternalType" Uuid="cccccccc-cccc-cccc-cccc-cccccccccccc"/>
  </Namespace>
</Catalogue:Catalogue>
`,
            'src/smdl-gen/generated.smpcat': `<?xml version="1.0" encoding="UTF-8"?>
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="ignored" Name="ignored"/>
`,
        });

        const services = await createBuiltinTestXsmpServices(NodeFileSystem);
        await services.shared.workspace.WorkspaceManager.initializeWorkspace([
            { name: 'app', uri: URI.file(projectDir).toString() },
        ]);

        const ignoredMirrorUri = services.shared.SmpWorkspaceIndex.getMirrorUriForSourcePath(path.join(projectDir, 'src', 'smdl-gen', 'generated.smpcat'));
        expect(ignoredMirrorUri).toBeUndefined();

        const project = services.shared.workspace.ProjectManager.getProjects().find(candidate => candidate.name === 'app');
        expect(project).toBeDefined();
        const report = await services.shared.DocumentGenerator.generateValidatedProject(project!, Cancellation.CancellationToken.None);

        expect(report.generatedProjects).toEqual(['app']);
        expect(fs.existsSync(path.join(projectDir, 'smdl-gen', 'types.smpcat'))).toBe(true);
        expect(fs.existsSync(path.join(projectDir, 'smdl-gen', 'types.smppkg'))).toBe(true);
    });

    test('switches from a real XSMP source to an SMP mirror after watched file updates', async () => {
        const foundationDir = createProject(tempDir, 'foundation', `
project 'foundation'
using 'ECSS_SMP_2025'
source 'src'
`, {
            'src/foundation_catalogue.xsmpcat': `
catalogue foundation_catalogue

namespace demo::foundation
{
    /** @uuid ffffffff-ffff-ffff-ffff-ffffffffffff */
    public struct ExternalType
    {
    }
}
`,
        });
        const avionicsDir = createProject(tempDir, 'avionics', `
project 'avionics'
using 'ECSS_SMP_2025'
source 'src'
dependency 'foundation'
`, {
            'src/avionics_catalogue.xsmpcat': `
catalogue avionics_catalogue

namespace demo::avionics
{
    /** @uuid 12121212-1212-1212-1212-121212121212 */
    struct UsesExternal
    {
        field demo.foundation.ExternalType external
    }
}
`,
        });

        const services = createXsmpServices(NodeFileSystem);
        await services.shared.ContributionRegistry.ready;
        await services.shared.workspace.WorkspaceManager.initializeWorkspace([
            { name: 'foundation', uri: URI.file(foundationDir).toString() },
            { name: 'avionics', uri: URI.file(avionicsDir).toString() },
        ]);

        const avionicsUri = URI.file(path.join(avionicsDir, 'src', 'avionics_catalogue.xsmpcat'));
        const avionicsDocumentBefore = services.shared.workspace.LangiumDocuments.getDocument(avionicsUri);
        expect(avionicsDocumentBefore?.diagnostics?.some(diagnostic => diagnostic.message.includes('Could not resolve reference'))).not.toBe(true);

        const foundationXsmpPath = path.join(foundationDir, 'src', 'foundation_catalogue.xsmpcat');
        const foundationSmpPath = path.join(foundationDir, 'src', 'foundation_catalogue.smpcat');
        fs.rmSync(foundationXsmpPath);
        fs.writeFileSync(foundationSmpPath, `<?xml version="1.0" encoding="UTF-8"?>
<!--Generated By SmpTool-1.97.0-->
<Catalogue:Catalogue xmlns:Catalogue="http://www.ecss.nl/smp/2025/Smdl/Catalogue" xmlns:Elements="http://www.ecss.nl/smp/2025/Core/Elements" xmlns:Types="http://www.ecss.nl/smp/2025/Core/Types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" Id="foundation" Name="foundation_catalogue">
  <Namespace Id="demo" Name="demo">
    <Namespace Id="demo.foundation" Name="foundation">
      <Type xsi:type="Types:Structure" Id="demo.foundation.ExternalType" Name="ExternalType" Visibility="public" Uuid="fefefefe-fefe-fefe-fefe-fefefefefefe"/>
    </Namespace>
  </Namespace>
</Catalogue:Catalogue>
`);

        const updateHandler = services.shared.lsp.DocumentUpdateHandler as unknown as {
            updateWatchedFiles(params: DidChangeWatchedFilesParams): Promise<void>;
        };

        await updateHandler.updateWatchedFiles({
            changes: [
                { uri: URI.file(foundationXsmpPath).toString(), type: FileChangeType.Deleted },
                { uri: URI.file(foundationSmpPath).toString(), type: FileChangeType.Created },
            ],
        });

        const mirrorUri = services.shared.SmpWorkspaceIndex.getMirrorUriForSourcePath(foundationSmpPath);
        expect(mirrorUri).toBeDefined();
        expect(mirrorUri && services.shared.workspace.LangiumDocuments.getDocument(mirrorUri)).toBeDefined();

        const avionicsDocumentAfter = services.shared.workspace.LangiumDocuments.getDocument(avionicsUri);
        expect(avionicsDocumentAfter?.diagnostics?.some(diagnostic => diagnostic.message.includes('Could not resolve reference'))).not.toBe(true);
    });
});

function createProject(rootDir: string, name: string, projectContent: string, files: Record<string, string>): string {
    const projectDir = path.join(rootDir, name);
    fs.mkdirSync(projectDir, { recursive: true });
    fs.writeFileSync(path.join(projectDir, 'xsmp.project'), projectContent.trimStart());

    for (const [relativePath, content] of Object.entries(files)) {
        const absolutePath = path.join(projectDir, relativePath);
        fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
        fs.writeFileSync(absolutePath, content.trimStart());
    }

    return projectDir;
}

function positionParams(document: LangiumDocument, offset: number): TextDocumentPositionParams {
    return {
        textDocument: { uri: document.textDocument.uri },
        position: document.textDocument.positionAt(offset),
    };
}

function expectMirrorLocation(
    locations: LocationLink[],
    mirrorUri: URI,
    mirrorDocument: LangiumDocument,
    token: string,
): void {
    expect(locations).toHaveLength(1);
    expect(locations[0].targetUri).toBe(mirrorUri.toString());
    const targetText = mirrorDocument.textDocument.getText();
    const start = targetText.indexOf(token);
    expect(start).toBeGreaterThanOrEqual(0);
    expect(locations[0].targetSelectionRange).toEqual({
        start: mirrorDocument.textDocument.positionAt(start),
        end: mirrorDocument.textDocument.positionAt(start + token.length),
    });
}
