import { beforeAll, describe, expect, test } from "vitest";
import { EmptyFileSystem, type LangiumDocument } from "langium";
import { expandToString as s } from "langium/generate";
import { parseHelper } from "langium/test";
import { createXsmpServices } from 'xsmp';
import * as ast from 'xsmp/ast';
import * as path from 'node:path';
import * as fs from 'node:fs';
import { ADocGenerator } from '@xsmp/tool-adoc';
import { setGeneratedBy } from 'xsmp/generator';

let services: ReturnType<typeof createXsmpServices>;
let parse: ReturnType<typeof parseHelper<ast.Catalogue>>;
let document: LangiumDocument<ast.Catalogue> | undefined;

beforeAll(async () => {
  services = createXsmpServices(EmptyFileSystem);
  parse = parseHelper<ast.Catalogue>(services.xsmpcat);

  await services.shared.workspace.WorkspaceManager.initializeWorkspace([]);
});

describe('ADoc generator tests', () => {



  test('test catalogue', async () => {

    const generator = new ADocGenerator(services.shared);
    document = await parse(fs.readFileSync(path.resolve(__dirname, 'Test.xsmpcat')).toString(), { documentUri: 'Test.xsmpcat' });
    // disable generated by comment
    setGeneratedBy(false);

    // check for absensce of parser errors the classic way:
    //  deacivated, find a much more human readable way below!
    // expect(document.parseResult.parserErrors).toHaveLength(0);
    expect(
      // here we use a (tagged) template expression to create a human readable representation
      //  of the AST part we are interested in and that is to be compared to our expectation;
      // prior to the tagged template expression we check for validity of the parsed document object
      //  by means of the reusable function 'checkDocumentValid()' to sort out (critical) typos first;
      checkDocumentValid(document) ??
      await generator.doGenerateCatalogue(document.parseResult.value)
    ).toBe(fs.readFileSync(path.resolve(__dirname, 'Test-gen.adoc')).toString());
  });
});

function checkDocumentValid(document: LangiumDocument): string | undefined {
  return document.parseResult.parserErrors.length && s`
        Parser errors:
          ${document.parseResult.parserErrors.map(e => e.message).join('\n  ')}
    `
    || document.parseResult.value === undefined && `ParseResult is 'undefined'.`
    || !ast.isCatalogue(document.parseResult.value) && `Root AST object is a ${document.parseResult.value.$type}, expected a '${ast.Catalogue.$type}'.`
    || undefined;
}
